### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by victorperin** [comunidadescampinas/agenda-api#12]
![image](https://user-images.githubusercontent.com/5847145/29982721-387049ee-8f29-11e7-95ac-bac8d8f145ab.png)

**Comment by fmoliveira** [comment]
Log da aplicação:

```
2017-09-01T18:51:45.085980+00:00 app[web.1]:   ReferenceError: err is not defined
2017-09-01T18:51:45.085982+00:00 app[web.1]:       at /app/src/server.js:20:16
2017-09-01T18:51:45.085983+00:00 app[web.1]:       at <anonymous>
2017-09-01T18:51:45.085984+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by victorperin** [comment]
Putz, provavelmente foi erro meu. To acostumado a usar o nome `error` do que resumir em err.
Ai esqueci de mudar o erro. (e ainda por cima, não testei essa parte. uhahuauha)

**Comment by victorperin** [comment]
Valeu @fmoliveira

**Comment by fmoliveira** [comment]
Suave! Eu compartilho a culpa, fiz merge sem testar ahuhuahua. Aceita o #13 que já sobe o fix. :)

**Comment by victorperin** [comment]
fixed #13
